### ISSUE TITLE
Адаптировать под ABAP 702.

### ISSUE THREAD

**Issue by Aleksoid1978** [AntonSikidin/zcl_docx#1]
Возможно ли адаптировать/переписать под ABAP 702 ?

**Comment by AntonSikidin** [comment]
Да можно,  что не так с 7.02, я так понимаю проблема в новом синтаксисе?

**Comment by AntonSikidin** [comment]
у меня нет доступа к 702, но есть 711, я перепишу в понедельник

**Comment by Aleksoid1978** [comment]
Ну да - синтаксис он не понимает. Но еще были проблемы с методами, уже точно не помню - вроде бы вот этого нет "cl_bcs_convert=>xtab_to_xstring".

**Comment by AntonSikidin** [comment]
адаптировал для 711, вроде должно и на 702 работать

**Comment by Aleksoid1978** [comment]
Проверил - все отлично работает.
Вопрос немного не по теме - мне надо генерить несколько документов в цикле, каких либо функций по "очистке/обнулению"  lcl_recursive_data и lcl_docx я не нашел. Как быть - каждый раз заново вызывать CREATE OBJECT ?

**Comment by AntonSikidin** [comment]
lcl_recursive_data да каждый раз создавать объект,  
lcl_docx не обязательно,  метод load_smw0  обновит все испульзуемые переменные, 

я так понимаю это один шаблон просто 50 разных документов,  
создавать новый объект lcl_docx не обязательно, но шаблон загрузить предется . потому что он портится, либо кешировать переменную lcl_docx->document либо каждый раз грузить из репозитария

**Comment by Aleksoid1978** [comment]
Все отлично работает, спасибо от души - можно сказать спас :)

**Comment by Aleksoid1978** [comment]
Опять же не совсем по теме - но по делу.
Предлагаю в вызов **lcl_docx->save()** добавить возврат сохраненного имени файла. Дабы можно было спокойно после сохранения не "придумывать" имя файла и взять и использовать.

**Comment by AntonSikidin** [comment]
пришлите пулреквест я приму

**Comment by Aleksoid1978** [comment]
Не в курсе как создавать пулреквесты.
Но прилагаю патч(для **ZCL_DOCX_CLASS_711.abap**) - **https://pastebin.com/926iH4UP**

**Comment by AntonSikidin** [comment]
готово
