### ISSUE TITLE
Добавить метод get_raw()

### ISSUE THREAD

**Issue by Aleksoid1978** [AntonSikidin/zcl_docx#2]
Добавить метод get_raw() для получения raw данных без сохранения на диск.
Патч - https://pastebin.com/yNM0rYv9

Я просто взял кусок кода из save() и немного причесал. в save() так же используется get_raw().

**Comment by AntonSikidin** [comment]
С патчами проблема, у меня на рабочей машине нет инструментов и прав, пришли текст целиком

**Comment by Aleksoid1978** [comment]
https://yadi.sk/d/-mikc33NRrVD-w

**Comment by AntonSikidin** [comment]
Добавил метод get_raw() . 

также добавил необязательный параметр iv_protect .
если он заполнен, то документ нельзя будет редактировать средствами офиса без ввода пароля который я уже не помню,
но это не спасает от последовательности ctrl+a -> ctrl+c -> ctrl+n -> ctrl+v  
для обычных пользователей это страшная магия

**Comment by AntonSikidin** [comment]
вот инструкция как присылать Pull Request,  так будет практичнее
[https://rustycrate.ru/руководства/2016/03/07/contributing.html ](https://rustycrate.ru/руководства/2016/03/07/contributing.html )
