### ISSUE TITLE
Transformations are invalid

### ISSUE THREAD

**Issue by sandraros** [AntonSikidin/zcl_docx#3]
I've got an issue with abapGit to clone your repository with +online.

The activation shows errors with XSLT transformations:

![image](https://user-images.githubusercontent.com/34005250/80966166-410bbd80-8e14-11ea-8e62-dbbe27d5253d.png)

The source code of all XSLT transformations are all truncated after approximately 255 characters

![image](https://user-images.githubusercontent.com/34005250/80966321-98aa2900-8e14-11ea-9daf-520ba378f959.png)

I think it's because they are stored in your repository with NEWLINE instead of the expected CRLF (what abapGit expects and what SAP expects in ABAP 7.52).

Maybe you use an old version of ABAP or an old version of abapGit?

**Comment by AntonSikidin** [comment]
merged

**Comment by AntonSikidin** [comment]
Please, check my online repo.

I do not have the technical ability

**Comment by sandraros** [comment]
Thank you. It works for this issue, concerning the XSLT source code. It's not truncated anymore:

![image](https://user-images.githubusercontent.com/34005250/81052224-5a1f7780-8ec3-11ea-8c80-0d475883dcae.png)

For information, I now see one minor problem, I will open a new issue (it's related to your old abapGit version; I use abapGit version: 1.94.0):

![image](https://user-images.githubusercontent.com/34005250/81062397-2732af00-8ed6-11ea-8814-4205b958b788.png)
