### ISSUE TITLE
Pull repository -> diff on zdocx_get_types.prog.xml (STATE & VARCL)

### ISSUE THREAD

**Issue by sandraros** [AntonSikidin/zcl_docx#5]
After pulling the repository, I see one minor problem concerning PROG ZDOCX_GET_TYPES, which I think is related to your old abapGit version (I use abapGit version: 1.94.0):

![image](https://user-images.githubusercontent.com/34005250/81062397-2732af00-8ed6-11ea-8814-4205b958b788.png)

Diff on /src/zdocx_get_types.prog.xml:
![image](https://user-images.githubusercontent.com/34005250/81062670-b5a73080-8ed6-11ea-891f-0d7eed03635f.png)

**Comment by AntonSikidin** [comment]
merged

**Comment by sandraros** [comment]
Nice. Everything is fine now:

![image](https://user-images.githubusercontent.com/34005250/81094147-63c8cf80-8f03-11ea-88b0-6768c821106d.png)
