### ISSUE TITLE
Is it compatible with WORD 97-2003?

### ISSUE THREAD

**Issue by ekekakos** [AntonSikidin/zcl_docx#9]
I want to attach a word to SAP S/4 HANA system and the DOCX file when I am trying to open says that "WORD FOUND UNREADABLE CONTENT ... " and it opens a new file and cannot transfer the changes back to the original word. If the word document's extension is DOC there is no problem, you can attach the file open it change it and save it.
But unfortunately your class crashes with the DOC files.
Is there anyway to overcome this?

Thanks
Elias

**Comment by AntonSikidin** [comment]
WORD 97-2003 is not supported because it has binary format instead zipped xml.
You must convert template to office2010 first
